version: "2"
services:
  upload-db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
  upload-ms:
    build: .
    # command: rails server -p 3000 -b '0.0.0.0' && rails db:reset && rails db:migrate
    # command: bash -c "sleep 40 && rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && bundle exec rails db:migrate"

    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - upload-db